spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  boot:
    admin:
      client:
        #        환경변수로 url 지정 필요. 일단은 기본 값 적용
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://localhost:9090}

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    com.sprint.mission.discodeit: info
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.springframework.web: info

discodeit:
  storage:
    local:
      root-path: local_storage
    type: local